export const CMP = [
    {
        AntiSeraName: "D",
        Abbreviation: "+D",
        ImmediateSpinRange: "",
        DegreeRange: "",
        AHQRange: "",
        CheckCellsRange: ""
    },
    {
        AntiSeraName: "C",
        Abbreviation: "+C",
        ImmediateSpinRange: "",
        DegreeRange: "",
        AHQRange: "",
        CheckCellsRange: ""
    }
];
export const RR_QC = [
    {
        reagentName:"Anti-A",
        Abbreviation:"alpha-A",
        AntiSeraLot:"1",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Anti-B",
        Abbreviation:"alpha-B",
        AntiSeraLot:"2",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Anti-A,B",
        Abbreviation:"alpha-A,B",
        AntiSeraLot:"3",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Anti-D",
        Abbreviation:"-alpha-D",
        AntiSeraLot:"4",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Control",
        Abbreviation:"Ctrl",
        AntiSeraLot:"5",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    }
]
export const TWO_CELL =[]
export const THREE_CELL =[]