export const CMP = [
    {
        AntiSeraName: "D",
        Abbreviation: "+D",
        ImmediateSpinRange: "",
        DegreeRange: "",
        AHQRange: "",
        CheckCellsRange: ""
    },
    {
        AntiSeraName: "C",
        Abbreviation: "+C",
        ImmediateSpinRange: "",
        DegreeRange: "",
        AHQRange: "",
        CheckCellsRange: ""
    }
];
export const RR_QC = [
    {
        reagentName:"Anti-A",
        Abbreviation:"\u03B1-A",
        AntiSeraLot:"1",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"Anti-B",
        Abbreviation:"\u03B1-B",
        AntiSeraLot:"2",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"Anti-A,B",
        Abbreviation:"\u03B1-A,B",
        AntiSeraLot:"3",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"Anti-D",
        Abbreviation:"\u03B1-D",
        AntiSeraLot:"4",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"Control",
        Abbreviation:"Ctrl",
        AntiSeraLot:"5",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"A1 Cells",
        Abbreviation:"Ctrl",
        AntiSeraLot:"6",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"B Cells",
        Abbreviation:"B",
        AntiSeraLot:"7",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"Screen Cell 1",
        Abbreviation:"SC1",
        AntiSeraLot:"8",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"Screen Cell 2",
        Abbreviation:"SC2",
        AntiSeraLot:"9",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    },
    {
        reagentName:"Screen Cell 3",
        Abbreviation:"SC3",
        AntiSeraLot:"10",
        ExpDate:"xx/xx/xx",
        ExpectedRange:"0"
    }
]
export const TWO_CELL =[
    {
        reagentName:"Screen Cell 1",
        Abbreviation:"SC1",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Screen Cell 2",
        Abbreviation:"SC2",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
]
export const THREE_CELL =[
    {
        reagentName:"Screen Cell 1",
        Abbreviation:"SC1",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Screen Cell 2",
        Abbreviation:"SC2",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },{
        reagentName:"Screen Cell 3",
        Abbreviation:"SC3",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    }
]

export const rh= [
    {
        reagentName:"Anti-D",
        Abbreviation:"D",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-C",
        Abbreviation:"C",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-E",
        Abbreviation:"E",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-c",
        Abbreviation:"c",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-e",
        Abbreviation:"e",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    }
]

export const kell= [
    {
        reagentName:"Anti-K",
        Abbreviation:"K",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-k",
        Abbreviation:"k",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-Kp\u1D43",
        Abbreviation:"Kp\u1D43",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-Kp\u1D47",
        Abbreviation:"Kp\u1D47",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-Js\u1D43",
        Abbreviation:"Js\u1D43",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-Js\u1D47",
        Abbreviation:"Js\u1D47",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    }
]

export const kidd= [
    {
        reagentName:"Anti-D",
        Abbreviation:"D",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-C",
        Abbreviation:"C",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-E",
        Abbreviation:"E",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-c",
        Abbreviation:"c",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    },
    {
        reagentName:"Anti-e",
        Abbreviation:"e",
        AntiSeraLot:"",
        ExpDate:"",
        ExpImmSpinRange:"1",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"0"
    }
]
