export const CMP = [
    {
        AntiSeraName: "D",
        Abbreviation: "+D",
        ImmediateSpinRange: "",
        DegreeRange: "",
        AHQRange: "",
        CheckCellsRange: ""
    },
    {
        AntiSeraName: "C",
        Abbreviation: "+C",
        ImmediateSpinRange: "",
        DegreeRange: "",
        AHQRange: "",
        CheckCellsRange: ""
    }
];
export const RR_QC = [
    {
        reagentName:"Anti-A",
        Abbreviation:"\u03B1-A",
        AntiSeraLot:"1",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Anti-B",
        Abbreviation:"\u03B1-B",
        AntiSeraLot:"2",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Anti-A,B",
        Abbreviation:"\u03B1-A,B",
        AntiSeraLot:"3",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Anti-D",
        Abbreviation:"\u03B1-D",
        AntiSeraLot:"4",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Control",
        Abbreviation:"Ctrl",
        AntiSeraLot:"5",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"A1 Cells",
        Abbreviation:"Ctrl",
        AntiSeraLot:"6",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"B Cells",
        Abbreviation:"B",
        AntiSeraLot:"7",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Screen Cell 1",
        Abbreviation:"SC1",
        AntiSeraLot:"8",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Screen Cell 2",
        Abbreviation:"SC2",
        AntiSeraLot:"9",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    },
    {
        reagentName:"Screen Cell 3",
        Abbreviation:"SC3",
        AntiSeraLot:"10",
        ExpDate:"Today",
        ExpectedRange:"Tomorrow"
    }
]
export const TWO_CELL =[]
export const THREE_CELL =[]