export const reagentRackQcData = [
    {
        reagentName:"Anti-A",
        Abbreviation:"\u03B1-A",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"Anti-B",
        Abbreviation:"\u03B1-B",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"Anti-A,B",
        Abbreviation:"\u03B1-A,B",
        AntiSeraLot:"3",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"Anti-D",
        Abbreviation:"\u03B1-D",
        AntiSeraLot:"4",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"Control",
        Abbreviation:"Ctrl",
        AntiSeraLot:"5",
        reagentExpDate:"",
        ExpectedRange:"0"
    },
    {
        reagentName:"A1 Cells",
        Abbreviation: "A<sub>1</sub>",
        AntiSeraLot:"6",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"B Cells",
        Abbreviation:"B",
        AntiSeraLot:"7",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"Screen Cell 1",
        Abbreviation:"SC1",
        AntiSeraLot:"8",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"Screen Cell 2",
        Abbreviation:"SC2",
        AntiSeraLot:"9",
        reagentExpDate:"",
        ExpectedRange:"1+"
    },
    {
        reagentName:"Screen Cell 3",
        Abbreviation:"SC3",
        AntiSeraLot:"10",
        reagentExpDate:"",
        ExpectedRange:"1+"
    }
]

export const qcData = {
"TwoCell": [
    {
        reagentName:"Screen Cell 1",
        Abbreviation:"SC1",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Screen Cell 2",
        Abbreviation:"SC2",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
],
"ThreeCell": [
    {
        reagentName:"Screen Cell 1",
        Abbreviation:"SC1",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Screen Cell 2",
        Abbreviation:"SC2",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },{
        reagentName:"Screen Cell 3",
        Abbreviation:"SC3",
        AntiSeraLot:"3",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"RhPos": [
    {
        reagentName:"Anti-D",
        Abbreviation:"D",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-C",
        Abbreviation:"C",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-E",
        Abbreviation:"E",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-c",
        Abbreviation:"c",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-e",
        Abbreviation:"e",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"RhNeg": [
    {
        reagentName:"Anti-D",
        Abbreviation:"D",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-C",
        Abbreviation:"C",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-E",
        Abbreviation:"E",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-c",
        Abbreviation:"c",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-e",
        Abbreviation:"e",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"KellPos": [
    {
        reagentName:"Anti-K",
        Abbreviation:"K",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-k",
        Abbreviation:"k",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Kp\u1D43",
        Abbreviation:"Kp\u1D43",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Kp\u1D47",
        Abbreviation:"Kp\u1D47",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Js\u1D43",
        Abbreviation:"Js\u1D43",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Js\u1D47",
        Abbreviation:"Js\u1D47",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"KellNeg": [
    {
        reagentName:"Anti-K",
        Abbreviation:"K",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-k",
        Abbreviation:"k",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Kp\u1D43",
        Abbreviation:"Kp\u1D43",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Kp\u1D47",
        Abbreviation:"Kp\u1D47",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Js\u1D43",
        Abbreviation:"Js\u1D43",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Js\u1D47",
        Abbreviation:"Js\u1D47",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"KiddPos": [
    {
        reagentName:"Anti-Le<sup>a</sup>",
        Abbreviation:"Le<sup>a</sup>",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Le<sup>b</sup>",
        Abbreviation:"Le<sup>b</sup>",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"KiddNeg": [
    {
        reagentName:"Anti-Le<sup>a</sup>",
        Abbreviation:"Le<sup>a</sup>",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Le<sup>b</sup>",
        Abbreviation:"Le<sup>b</sup>",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"DuffyPos": [
    {
        reagentName:"Anti-Fy<sup>a</sup>",
        Abbreviation:"Fy<sup>a</sup>",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Fy<sup>b</sup>",
        Abbreviation:"Fy<sup>b</sup>",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"DuffyNeg": [
    {
        reagentName:"Anti-Fy<sup>a</sup>",
        Abbreviation:"Fy<sup>a</sup>",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Fy<sup>b</sup>",
        Abbreviation:"Fy<sup>b</sup>",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"MNSsPos": [
    {
        reagentName:"Anti-M",
        Abbreviation:"M",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-N",
        Abbreviation:"N",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-S",
        Abbreviation:"N",
        AntiSeraLot:"3",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-s",
        Abbreviation:"s",
        AntiSeraLot:"4",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"MNSsNeg": [
    {
        reagentName:"Anti-M",
        Abbreviation:"M",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-N",
        Abbreviation:"N",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-S",
        Abbreviation:"N",
        AntiSeraLot:"3",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-s",
        Abbreviation:"s",
        AntiSeraLot:"4",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"LutheranPos": [
    {
        reagentName:"Anti-Lu<sup>a</sup>",
        Abbreviation:"Lu<sup>a</sup>",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Lu<sup>b</sup>",
        Abbreviation:"Lu<sup>b</sup>",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"LutheranNeg": [
    {
        reagentName:"Anti-Lu<sup>a</sup>",
        Abbreviation:"Lu<sup>a</sup>",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
    {
        reagentName:"Anti-Lu<sup>b</sup>",
        Abbreviation:"Lu<sup>b</sup>",
        AntiSeraLot:"2",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    }
],
"P1Pos": [
    {
        reagentName:"Anti-P1",
        Abbreviation:"P1",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },
],
"P1Neg": [
    {
        reagentName:"Anti-P1",
        Abbreviation:"P1",
        AntiSeraLot:"1",
        reagentExpDate:"",
        ExpImmSpinRange:"0",
        Exp37Range:"0",
        ExpAHGRange:"0",
        ExpCheckCellsRange:"1+"
    },  
]
}