export const CMP = [
  {
    analyteName: "Sodium",
    analyteAcronym: "Na",
    unit_of_measure: "mEq/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Potassium",
    analyteAcronym: "K",
    unit_of_measure: "mEq/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Chloride",
    analyteAcronym: "Cl",
    unit_of_measure: "mEq/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Carbon Dioxide",
    analyteAcronym: "CO_2",
    unit_of_measure: "mEq/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Blood Urea Nitrogen",
    analyteAcronym: "BUN",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "52",
    sdplus1: 23,
    sdplus2: 56,
    sdplus3: 10,
    sdminus1: 85,
    sdminus2: 71,
    sdminus3: 33,
    electrolyte: false,
  },
  {
    analyteName: "Creatinine",
    analyteAcronym: "CREA",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "20",
    sdplus1: 20,
    sdplus2: 91,
    sdplus3: 58,
    sdminus1: 4,
    sdminus2: 24,
    sdminus3: 10,
    electrolyte: false,
  },
  {
    analyteName: "Calcium",
    analyteAcronym: "CA",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "62",
    sdplus1: 90,
    sdplus2: 59,
    sdplus3: 33,
    sdminus1: 26,
    sdminus2: 20,
    sdminus3: 1,
    electrolyte: false,
  },
  {
    analyteName: "Glucose",
    analyteAcronym: "GLU",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "57",
    sdplus1: 15,
    sdplus2: 92,
    sdplus3: 20,
    sdminus1: 54,
    sdminus2: 10,
    sdminus3: 18,
    electrolyte: false,
  },
  {
    analyteName: "Albumin",
    analyteAcronym: "ALB",
    unit_of_measure: "g/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "95",
    sdplus1: 92,
    sdplus2: 26,
    sdplus3: 53,
    sdminus1: 68,
    sdminus2: 81,
    sdminus3: 24,
    electrolyte: false,
  },
  {
    analyteName: "Alanine Aminotransferase",
    analyteAcronym: "ALT",
    unit_of_measure: "U/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "35",
    sdplus1: 68,
    sdplus2: 87,
    sdplus3: 90,
    sdminus1: 24,
    sdminus2: 74,
    sdminus3: 87,
    electrolyte: false,
  },
  {
    analyteName: "Aspartate Aminotransferase",
    analyteAcronym: "AST",
    unit_of_measure: "U/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "10",
    sdplus1: 30,
    sdplus2: 94,
    sdplus3: 43,
    sdminus1: 57,
    sdminus2: 78,
    sdminus3: 31,
    electrolyte: false,
  },
  {
    analyteName: "Akaline Phosphatse",
    analyteAcronym: "ALP",
    unit_of_measure: "U/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "42",
    sdplus1: 33,
    sdplus2: 91,
    sdplus3: 97,
    sdminus1: 32,
    sdminus2: 17,
    sdminus3: 70,
    electrolyte: false,
  },
  {
    analyteName: "Bilirubin",
    analyteAcronym: "BIL",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "23",
    sdplus1: 53,
    sdplus2: 26,
    sdplus3: 20,
    sdminus1: 59,
    sdminus2: 32,
    sdminus3: 73,
    electrolyte: false,
  },
  {
    analyteName: "Total Protein",
    analyteAcronym: "TP",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "15",
    sdplus1: 29,
    sdplus2: 39,
    sdplus3: 17,
    sdminus1: 48,
    sdminus2: 45,
    sdminus3: 68,
    electrolyte: false,
  },
];


export const Cardiac = [
{
  analyteName: "Trroponin-I",
  analyteAcronym: "T",
  unit_of_measure: "ng/mL",
  min_level: "0",
  max_level: "0",
  mean: "0",
  std_devi: "73",
  sdplus1: 42,
  sdplus2: 57,
  sdplus3: 94,
  sdminus1: 30,
  sdminus2: 44,
  sdminus3: 34,
  electrolyte: true,
},
{
  analyteName: "Creatine kinase",
  analyteAcronym: "CK",
  unit_of_measure: "U/L",
  min_level: "0",
  max_level: "0",
  mean: "0",
  std_devi: "67",
  sdplus1: 86,
  sdplus2: 62,
  sdplus3: 99,
  sdminus1: 4,
  sdminus2: 52,
  sdminus3: 20,
  electrolyte: true,
},
{
  analyteName: "Creatine kinase-MB",
  analyteAcronym: "CK-MB",
  unit_of_measure: "%",
  min_level: "0",
  max_level: "0",
  mean: "0",
  std_devi: "16",
  sdplus1: 100,
  sdplus2: 21,
  sdplus3: 42,
  sdminus1: 81,
  sdminus2: 31,
  sdminus3: 91,
  electrolyte: true,
},
{
  analyteName: "Myoglobin",
  analyteAcronym: "MYO",
  unit_of_measure: "ng/mL",
  min_level: "0",
  max_level: "0",
  mean: "0",
  std_devi: "87",
  sdplus1: 32,
  sdplus2: 68,
  sdplus3: 28,
  sdminus1: 53,
  sdminus2: 36,
  sdminus3: 32,
  electrolyte: true,
},
{
  analyteName: "High-sensitivity C-reactive protein",
  analyteAcronym: "hsCRP",
  unit_of_measure: "mg/dL",
  min_level: "0",
  max_level: "0",
  mean: "0",
  std_devi: "52",
  sdplus1: 23,
  sdplus2: 56,
  sdplus3: 10,
  sdminus1: 85,
  sdminus2: 71,
  sdminus3: 33,
  electrolyte: false,
},
];






export const Thyroid = [
  {
    analyteName: "Thyroid-stimulating hormone",
    analyteAcronym: " TSH",
    unit_of_measure: "µIU/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Tiiiodothyronine, Total",
    analyteAcronym: "T₃",
    unit_of_measure: "ng/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Thyrooxine,Total",
    analyteAcronym: "T₄",
    unit_of_measure: "ng/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "tiiiodothyronine, Free",
    analyteAcronym: "FT₃",
    unit_of_measure: "mEq/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Thyroxiine, Free",
    analyteAcronym: "FT₄",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "52",
    sdplus1: 23,
    sdplus2: 56,
    sdplus3: 10,
    sdminus1: 85,
    sdminus2: 71,
    sdminus3: 33,
    electrolyte: false,
  },
  {
    analyteName: "Anti-Thyroperoxidase",
    analyteAcronym: "TPOAb",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "20",
    sdplus1: 20,
    sdplus2: 91,
    sdplus3: 58,
    sdminus1: 4,
    sdminus2: 24,
    sdminus3: 10,
    electrolyte: false,
  },
  {
    analyteName: "Anti-Thyroglobulin",
    analyteAcronym: "TgAB",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "62",
    sdplus1: 90,
    sdplus2: 59,
    sdplus3: 33,
    sdminus1: 26,
    sdminus2: 20,
    sdminus3: 1,
    electrolyte: false,
  },
];
  







export const Liver = [
  {
    analyteName: "Alanine Aminotransferase",
    analyteAcronym: " ALT",
    unit_of_measure: "U/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Aspartate Aminotransferase",
    analyteAcronym: "AST",
    unit_of_measure: "U/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Akaline Phosphatse",
    analyteAcronym: "ALP",
    unit_of_measure: "U/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Gamma-glutamyl transferase",
    analyteAcronym: "GGT",
    unit_of_measure: "U/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Albumin",
    analyteAcronym: "ALB",
    unit_of_measure: "g/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "52",
    sdplus1: 23,
    sdplus2: 56,
    sdplus3: 10,
    sdminus1: 85,
    sdminus2: 71,
    sdminus3: 33,
    electrolyte: false,
  },
  {
    analyteName: "Bilirubin",
    analyteAcronym: "BIL",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "20",
    sdplus1: 20,
    sdplus2: 91,
    sdplus3: 58,
    sdminus1: 4,
    sdminus2: 24,
    sdminus3: 10,
    electrolyte: false,
  },
  {
    analyteName: "Total Protein",
    analyteAcronym: "TP",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "62",
    sdplus1: 90,
    sdplus2: 59,
    sdplus3: 33,
    sdminus1: 26,
    sdminus2: 20,
    sdminus3: 1,
    electrolyte: false,
  },
];
  
















export const Lipid = [
  {
    analyteName: "Cholestoral",
    analyteAcronym: " CholL",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "High-Density Lipoprotein",
    analyteAcronym: "HDL",
    unit_of_measure: "mg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Low-Density Lipoprotein",
    analyteAcronym: "LDL",
    unit_of_measure: "mg/dl",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Triglycerides, Total",
    analyteAcronym: "Trig",
    unit_of_measure: "mg/dl",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
];
  









export const Iron = [
  {
    analyteName: "Iron, Total",
    analyteAcronym: " Fe",
    unit_of_measure: "µg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Total Iron Binding Capacity",
    analyteAcronym: "TIBC",
    unit_of_measure: "µg/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Transferrin Saturation",
    analyteAcronym: "TS",
    unit_of_measure: "mg/dl",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Ferritin",
    analyteAcronym: "Ferr",
    unit_of_measure: "ng/dl",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
];
  








export const Drug = [
  {
    analyteName: "Ampetamines",
    analyteAcronym: " AMP",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Cannabinoids",
    analyteAcronym: "THC",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Cocaine",
    analyteAcronym: "COC",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Opiates",
    analyteAcronym: "OPI",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Phencyclidine",
    analyteAcronym: " pcp",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Barbiturates",
    analyteAcronym: "BARB",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Benzodiazepines",
    analyteAcronym: "BENZ",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Methadone",
    analyteAcronym: "METH",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Propoxyphene",
    analyteAcronym: "PRO",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Ethanol",
    analyteAcronym: "ETOH",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
];











export const Hormone = [
  {
    analyteName: "Total Testosterone",
    analyteAcronym: " TEST",
    unit_of_measure: "ng/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Free Testosterone",
    analyteAcronym: "fTEST",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Prostate-specific Antigen-Total",
    analyteAcronym: "tPSA",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Prostate-specific Antigen-Free",
    analyteAcronym: "fPSA",
    unit_of_measure: "%",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Estriadol",
    analyteAcronym: "E2",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Follicle-Stimulating Hormone",
    analyteAcronym: "FSH",
    unit_of_measure: "mIU/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Luteinizing Hormone",
    analyteAcronym: "LH",
    unit_of_measure: "IU/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Progesterone",
    analyteAcronym: "PROG",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Sex Hormone Binding Globulin",
    analyteAcronym: "SHBG",
    unit_of_measure: "nmol/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Human Chorionic Gonadotropin-Total",
    analyteAcronym: "hCGT",
    unit_of_measure: "mIU/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
];



export const Pancreatic = [
  {
    analyteName: "Amylase",
    analyteAcronym: " AMY",
    unit_of_measure: "ng/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Lactase",
    analyteAcronym: "LIP",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Lactate Dehydrogenase",
    analyteAcronym: "LDH",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true
  },
];



export const Diabetes = [
  {
    analyteName: "Glycated Hemoglobin",
    analyteAcronym: " HgbA1c",
    unit_of_measure: "ng/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Magnesium",
    analyteAcronym: "MG",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Phosphorous",
    analyteAcronym: "Phos",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  }
];





export const Cancer = [
  {
    analyteName: "Carcinoembryonic Antigen",
    analyteAcronym: " CEA",
    unit_of_measure: "ng/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Cancer Antigen 125",
    analyteAcronym: "CA 125",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "Carbohydrate Antigen 19-9",
    analyteAcronym: "CA 19-9",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Cancer Antigen 15-3",
    analyteAcronym: "CA 15-3",
    unit_of_measure: "%",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Cancer Antigen 27.29",
    analyteAcronym: "CA 27.29",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
];


export const Vitamins = [
  {
    analyteName: "Vitamin B12",
    analyteAcronym: " B12",
    unit_of_measure: "ng/dL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "73",
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
    electrolyte: true,
  },
  {
    analyteName: "Vitamin B6",
    analyteAcronym: "B6",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "67",
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
    electrolyte: true,
  },
  {
    analyteName: "25-Hydroxy Vitamin D",
    analyteAcronym: "Vit D",
    unit_of_measure: "ng/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "16",
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
    electrolyte: true,
  },
  {
    analyteName: "Vitamin A",
    analyteAcronym: "Vit A",
    unit_of_measure: "%",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Vitamin C",
    analyteAcronym: "Vit C",
    unit_of_measure: "pg/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: "Homocysteine",
    analyteAcronym: "HCY",
    unit_of_measure: "mIU/mL",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
  {
    analyteName: " Folate",
    analyteAcronym: "FOL",
    unit_of_measure: "IU/L",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "87",
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
    electrolyte: true,
  },
];
