export const CMP = [
  {
    "analyteName": "Sodium",
    "analyteAcronym": "Na",
    "unitOfMeasure": "mEq/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Potassium",
    "analyteAcronym": "K",
    "unitOfMeasure": "mEq/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Chloride",
    "analyteAcronym": "Cl",
    "unitOfMeasure": "mEq/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Carbon Dioxide",
    "analyteAcronym": "CO_2",
    "unitOfMeasure": "mEq/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Blood Urea Nitrogen",
    "analyteAcronym": "BUN",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Creatinine",
    "analyteAcronym": "CREA",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Calcium, Total",
    "analyteAcronym": "CA",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Glucose",
    "analyteAcronym": "GLU",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Albumin",
    "analyteAcronym": "ALB",
    "unitOfMeasure": "g/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Alanine Aminotransferase",
    "analyteAcronym": "ALT",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Aspartate Aminotransferase",
    "analyteAcronym": "AST",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Alkaline Phosphatse",
    "analyteAcronym": "ALP",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Bilirubin, Total",
    "analyteAcronym": "tBIL",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Total Protein",
    "analyteAcronym": "TP",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];


export const Cardiac = [
{
  "analyteName": "Troponin-I",
  "analyteAcronym": "cTnl",
  "unitOfMeasure": "ng/mL",
  "minLevel": "",
  "maxLevel": "",
  "mean": "",
  "stdDevi": ""
},
{
  "analyteName": "Creatine Kinase",
  "analyteAcronym": "CK",
  "unitOfMeasure": "U/L",
  "minLevel": "",
  "maxLevel": "",
  "mean": "",
  "stdDevi": ""
},
{
  "analyteName": "Creatine Kinase-MB",
  "analyteAcronym": "CK-MB",
  "unitOfMeasure": "%",
  "minLevel": "",
  "maxLevel": "",
  "mean": "",
  "stdDevi": ""
},
{
  "analyteName": "Myoglobin",
  "analyteAcronym": "MYO",
  "unitOfMeasure": "ng/mL",
  "minLevel": "",
  "maxLevel": "",
  "mean": "",
  "stdDevi": ""
},
{
  "analyteName": "High-sensitivity C-reactive Protein",
  "analyteAcronym": "hsCRP",
  "unitOfMeasure": "mg/dL",
  "minLevel": "",
  "maxLevel": "",
  "mean": "",
  "stdDevi": ""
},
];

export const Thyroid = [
  {
    "analyteName": "Thyroid-Stimulating Hormone",
    "analyteAcronym": "TSH",
    "unitOfMeasure": "\u03BCIU/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Triiodothyronine, Total",
    "analyteAcronym": "T3",
    "unitOfMeasure": "ng/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Thyroxine,Total",
    "analyteAcronym": "T4",
    "unitOfMeasure": "\u03BCg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Triiodothyronine, Free",
    "analyteAcronym": "FT₃",
    "unitOfMeasure": "pg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Thyroxine, Free",
    "analyteAcronym": "FT₄",
    "unitOfMeasure": "ng/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Anti-Thyroid Peroxidase",
    "analyteAcronym": "TPOAb",
    "unitOfMeasure": "IU/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Anti-Thyroglobulin",
    "analyteAcronym": "TgAB",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];
  
export const Liver = [
  {
    "analyteName": "Alanine Aminotransferase",
    "analyteAcronym": "ALT",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Aspartate Aminotransferase",
    "analyteAcronym": "AST",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Alkaline Phosphatase",
    "analyteAcronym": "ALP",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Gamma Glutamyl Transferase",
    "analyteAcronym": "GGT",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Albumin",
    "analyteAcronym": "ALB",
    "unitOfMeasure": "g/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Bilirubin, Total",
    "analyteAcronym": "tBIL",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Total Protein",
    "analyteAcronym": "TP",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];
  
export const Lipid = [
  {
    "analyteName": "Cholestorol, Total",
    "analyteAcronym": "Chol",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "High-Density Lipoproteins",
    "analyteAcronym": "HDL",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Low-Density Lipoproteins",
    "analyteAcronym": "LDL",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Triglycerides, Total",
    "analyteAcronym": "Trig",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];

export const Iron = [
  {
    "analyteName": "Iron, Total",
    "analyteAcronym": "Fe",
    "unitOfMeasure": "\u03BCg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Total Iron Binding Capacity",
    "analyteAcronym": "TIBC",
    "unitOfMeasure": "\u03BCg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Transferrin Saturation",
    "analyteAcronym": "TS",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Ferritin",
    "analyteAcronym": "Ferr",
    "unitOfMeasure": "ng/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];

export const Drug = [
  {
    "analyteName": "Amphetamines",
    "analyteAcronym": "AMP",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Cannabinoids",
    "analyteAcronym": "THC",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Cocaine",
    "analyteAcronym": "COC",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Opiates",
    "analyteAcronym": "OPI",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Phencyclidine",
    "analyteAcronym": "PCP",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Barbiturates",
    "analyteAcronym": "BARB",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Benzodiazepines",
    "analyteAcronym": "BENZ",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Methadone",
    "analyteAcronym": "METH",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Propoxyphene",
    "analyteAcronym": "PRO",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Ethanol",
    "analyteAcronym": "ETOH",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];

export const Hormone = [
  {
    "analyteName": "Total Testosterone",
    "analyteAcronym": "TEST",
    "unitOfMeasure": "ng/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "free Testosterone",
    "analyteAcronym": "fTEST",
    "unitOfMeasure": "pg/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Prostate Specific Antigen-Total",
    "analyteAcronym": "tPSA",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Prostate Specific Antigen-Free",
    "analyteAcronym": "fPSA",
    "unitOfMeasure": "%",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Estriadol",
    "analyteAcronym": "E2",
    "unitOfMeasure": "pg/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Follicle Stimulating Hormone",
    "analyteAcronym": "FSH",
    "unitOfMeasure": "mIU/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Luteinizing Hormone",
    "analyteAcronym": "LH",
    "unitOfMeasure": "IU/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Progesterone",
    "analyteAcronym": "PROG",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Sex Hormone Binding Globulin",
    "analyteAcronym": "SHBG",
    "unitOfMeasure": "nmol/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Human Chorionic Gonadotropin-Total",
    "analyteAcronym": "hCGT",
    "unitOfMeasure": "mIU/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];

export const Pancreatic = [
  {
    "analyteName": "Amylase",
    "analyteAcronym": "AMY",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Lipase",
    "analyteAcronym": "LIP",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Lactate Dehydrogenase",
    "analyteAcronym": "LDH",
    "unitOfMeasure": "U/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];



export const Diabetes = [
  {
    "analyteName": "Glycated Hemoglobin",
    "analyteAcronym": "HgbA1c",
    "unitOfMeasure": "% of total Hb",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Magnesium",
    "analyteAcronym": "Mg",
    "unitOfMeasure": "mEq/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Phosphorous",
    "analyteAcronym": "Phos",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  }
];

export const Cancer = [
  {
    "analyteName": "Carcinoembryonic Antigen",
    "analyteAcronym": "CEA",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Cancer Antigen 125",
    "analyteAcronym": "CA 125",
    "unitOfMeasure": "U/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Carbohydrate Antigen 19-9",
    "analyteAcronym": "CA 19-9",
    "unitOfMeasure": "U/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Cancer Antigen 15-3",
    "analyteAcronym": "CA 15-3",
    "unitOfMeasure": "U/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Cancer Antigen 27.29",
    "analyteAcronym": "CA 27.29",
    "unitOfMeasure": "U/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];


export const Vitamins = [
  {
    "analyteName": "Vitamin B12",
    "analyteAcronym": "B12",
    "unitOfMeasure": "pg/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Vitamin B6",
    "analyteAcronym": "B6",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "25-Hydroxy Vitamin D",
    "analyteAcronym": "Vit D",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Vitamin A",
    "analyteAcronym": "Vit A",
    "unitOfMeasure": "\u03BCg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Vitamin C",
    "analyteAcronym": "Vit C",
    "unitOfMeasure": "mg/dL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Homocysteine",
    "analyteAcronym": "HCY",
    "unitOfMeasure": "\u03BCmol/L",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
  {
    "analyteName": "Folate",
    "analyteAcronym": "FOL",
    "unitOfMeasure": "ng/mL",
    "minLevel": "",
    "maxLevel": "",
    "mean": "",
    "stdDevi": "",
  },
];
