export const mock = [
  {
    analyteName: "Sodium",
    analyteAcronym: "Na",
    unit_of_measure: "TK",
    min_level: 76,
    max_level: 13,
    mean: 45,
    std_devi: 73,
    sdplus1: 42,
    sdplus2: 57,
    sdplus3: 94,
    sdminus1: 30,
    sdminus2: 44,
    sdminus3: 34,
  },
  {
    analyteName: "Potassium",
    analyteAcronym: "K",
    unit_of_measure: "PAACU",
    min_level: 55,
    max_level: 3,
    mean: 77,
    std_devi: 67,
    sdplus1: 86,
    sdplus2: 62,
    sdplus3: 99,
    sdminus1: 4,
    sdminus2: 52,
    sdminus3: 20,
  },
  {
    analyteName: "Chloride",
    analyteAcronym: "Cl",
    unit_of_measure: "FAC",
    min_level: 85,
    max_level: 89,
    mean: 5,
    std_devi: 16,
    sdplus1: 100,
    sdplus2: 21,
    sdplus3: 42,
    sdminus1: 81,
    sdminus2: 31,
    sdminus3: 91,
  },
  {
    analyteName: "Carbon Dioxide",
    analyteAcronym: "CO_2",
    unit_of_measure: "GSL^B",
    min_level: 46,
    max_level: 46,
    mean: 43,
    std_devi: 87,
    sdplus1: 32,
    sdplus2: 68,
    sdplus3: 28,
    sdminus1: 53,
    sdminus2: 36,
    sdminus3: 32,
  },
  {
    analyteName: "Blood Urea Nitrogen",
    analyteAcronym: "BUN",
    unit_of_measure: "REN",
    min_level: 57,
    max_level: 48,
    mean: 25,
    std_devi: 52,
    sdplus1: 23,
    sdplus2: 56,
    sdplus3: 10,
    sdminus1: 85,
    sdminus2: 71,
    sdminus3: 33,
  },
  {
    analyteName: "Creatinine",
    analyteAcronym: "CREA",
    unit_of_measure: "AAME",
    min_level: 7,
    max_level: 35,
    mean: 11,
    std_devi: 20,
    sdplus1: 20,
    sdplus2: 91,
    sdplus3: 58,
    sdminus1: 4,
    sdminus2: 24,
    sdminus3: 10,
  },
  {
    analyteName: "Calcium",
    analyteAcronym: "CA",
    unit_of_measure: "PFD",
    min_level: 39,
    max_level: 20,
    mean: 23,
    std_devi: 62,
    sdplus1: 90,
    sdplus2: 59,
    sdplus3: 33,
    sdminus1: 26,
    sdminus2: 20,
    sdminus3: 1,
  },
  {
    analyteName: "Glucose",
    analyteAcronym: "GLU",
    unit_of_measure: "CENX",
    min_level: 92,
    max_level: 69,
    mean: 29,
    std_devi: 57,
    sdplus1: 15,
    sdplus2: 92,
    sdplus3: 20,
    sdminus1: 54,
    sdminus2: 10,
    sdminus3: 18,
  },
  {
    analyteName: "Albumin",
    analyteAcronym: "ALB",
    unit_of_measure: "SHLX",
    min_level: 93,
    max_level: 53,
    mean: 50,
    std_devi: 95,
    sdplus1: 92,
    sdplus2: 26,
    sdplus3: 53,
    sdminus1: 68,
    sdminus2: 81,
    sdminus3: 24,
  },
  {
    analyteName: "Alanine Aminotransferase",
    analyteAcronym: "ALT",
    unit_of_measure: "GDV^D",
    min_level: 65,
    max_level: 42,
    mean: 96,
    std_devi: 35,
    sdplus1: 68,
    sdplus2: 87,
    sdplus3: 90,
    sdminus1: 24,
    sdminus2: 74,
    sdminus3: 87,
  },
  {
    analyteName: "Aspartate Aminotransferase",
    analyteAcronym: "AST",
    unit_of_measure: "AXGN",
    min_level: 73,
    max_level: 28,
    mean: 60,
    std_devi: 10,
    sdplus1: 30,
    sdplus2: 94,
    sdplus3: 43,
    sdminus1: 57,
    sdminus2: 78,
    sdminus3: 31,
  },
  {
    analyteName: "Akaline Phosphatse",
    analyteAcronym: "ALP",
    unit_of_measure: "FFIC",
    min_level: 13,
    max_level: 66,
    mean: 98,
    std_devi: 42,
    sdplus1: 33,
    sdplus2: 91,
    sdplus3: 97,
    sdminus1: 32,
    sdminus2: 17,
    sdminus3: 70,
  },
  {
    analyteName: "Bilirubin",
    analyteAcronym: "BIL",
    unit_of_measure: "RXIIW",
    min_level: 17,
    max_level: 73,
    mean: 8,
    std_devi: 23,
    sdplus1: 53,
    sdplus2: 26,
    sdplus3: 20,
    sdminus1: 59,
    sdminus2: 32,
    sdminus3: 73,
  },
  {
    analyteName: "Total Protein",
    analyteAcronym: "TP",
    unit_of_measure: "FMX",
    min_level: 60,
    max_level: 26,
    mean: 65,
    std_devi: 15,
    sdplus1: 29,
    sdplus2: 39,
    sdplus3: 17,
    sdminus1: 48,
    sdminus2: 45,
    sdminus3: 68,
  },
];
