export const Dip = [
    {
      analyteName: "Glucose",
      analyteAcronym: "GLU",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Trace", "1+", "2+", "3+", "4+"],
      
    },
    {
      analyteName: "Bilirubin",
      analyteAcronym: "BIL",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Small", "Moderate", "Large"],
    },
    {
      analyteName: "Ketone",
      analyteAcronym: "KET",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Trace", "Small", "Moderate", "Large"],
      
    },
    {
      analyteName: "Specific Gravity",
      analyteAcronym: "SG",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["1.000", "1.005", "1.010", "1.015", "1.020", "1.025", "1.030"],
    },
    {
      analyteName: "Blood",
      analyteAcronym: "BLO",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: false,
      expected_range: ["Neg", "Trace", "Small", "Moderate", "Large"],
    },
    {
      analyteName: "pH",
      analyteAcronym: "pH",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: false,
      expected_range: ["5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5"],
    },
    {
      analyteName: "Protein",
      analyteAcronym: "PRO",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: false,
      expected_range: ["Neg", "Trace", "1+", "2+", "3+", "4+"],
    },
    {
      analyteName: "Urobilinogen",
      analyteAcronym: "URO",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: false,
      expected_range: ["0.2", "1.0", "2.0", "4.0", "8.0"],
    },
    {
      analyteName: "Nitrite",
      analyteAcronym: "NIT",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: false,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Leukocyte Esterase​",
      analyteAcronym: "LEU",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: false,
      expected_range: ["Neg", "Trace", "Small", "Moderate", "Large"],
    },
  ];
  
  
  export const Osmolality = [
    {
      analyteName: "Osmolality Low",
      analyteAcronym: "Osmo-L",
      unit_of_measure: "mmol/kgH20",
      min_level: "28",
      max_level: "29",
      mean: "40",
      std_devi: "60",
      sdplus1: 86,
      sdplus2: 62,
      sdplus3: 99,
      sdminus1: 4,
      sdminus2: 52,
      sdminus3: 20,
      electrolyte: true,
      
    },
    {
      analyteName: "Osmolality High",
      analyteAcronym: "Osmo-H",
      unit_of_measure: "mmol/kgH20",
      min_level: "28",
      max_level: "29",
      mean: "40",
      std_devi: "60",
      sdplus1: 86,
      sdplus2: 62,
      sdplus3: 99,
      sdminus1: 4,
      sdminus2: 52,
      sdminus3: 20,
      electrolyte: true,
    },
  ];
  
  
  export const DrugScreen = [
    {
      analyteName: "Amphetamines",
      analyteAcronym: " AMP",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Alcohol",
      analyteAcronym: "ETOH",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Barbiturates",
      analyteAcronym: "BAR",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Benzodiazepines",
      analyteAcronym: "BZO",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Cocaine",
      analyteAcronym: "COC",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Cannabinoids",
      analyteAcronym: "THC",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Opiates",
      analyteAcronym: "OPI",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Phencyclidine",
      analyteAcronym: "PCP",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Tricyclic Antidepressants",
      analyteAcronym: "TCA",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Oxycodone",
      analyteAcronym: "OXY",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Methadone",
      analyteAcronym: "MTD",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Methamphetamine",
      analyteAcronym: "MAMP",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "3,4 Methylenedioxymethamphetamine",
      analyteAcronym: "MDMA",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Propoxyphene",
      analyteAcronym: "PPX",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
  ];

  export const Clinitest = [
    {
      analyteName: "Clinitest positive",
      analyteAcronym: "Clini+",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Clinitest negative",
      analyteAcronym: "Clini-",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
  ];

  export const Ictotest = [
    {
      analyteName: "Ictotest Positive",
      analyteAcronym: "Icto+",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Ictotest Negative",
      analyteAcronym: "Icto-",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
  ];

  export const Acetest = [
    {
      analyteName: "Acetest Positive",
      analyteAcronym: "Ace+",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
    {
      analyteName: "Acetest Negative",
      analyteAcronym: "Ace-",
      unit_of_measure: "N/A",
      min_level: "0",
      max_level: "0",
      mean: "0",
      std_devi: "0",
      sdplus1: 0,
      sdplus2: 0,
      sdplus3: 0,
      sdminus1: 0,
      sdminus2: 0,
      sdminus3: 0,
      electrolyte: true,
      expected_range: ["Neg", "Pos"],
    },
  ];   
  

  //Body fluids Panles and Analytes 
export const BFAnalytes = [
  {
    analyteName: "Body Fluid RBC Count",
    analyteAcronym: "BF-RBC",
    unit_of_measure: "/hpf",
    min_level: "2",
    max_level: "25",
    mean: "20",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: [],
  },
  {
    analyteName: "Body Fluid Total Nucleated Cells",
    analyteAcronym: "BF-TNC",
    unit_of_measure: "/hpf",
    min_level: "45",
    max_level: "75",
    mean: "49",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: [],
  }
];

export const BFcrystals = [
  {
    analyteName: "Fluid Crystal Positive",
    analyteAcronym: "FC+",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Fluid Crystal Negative",
    analyteAcronym: "FC-",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Monosodium Urate",
    analyteAcronym: "MSU",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Calcium Pyrophosphate Dihydrate",
    analyteAcronym: "CPPD",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Cholesterol",
    analyteAcronym: "CHOL",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Steroids",
    analyteAcronym: "STER",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Apatite",
    analyteAcronym: "APA",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Phosphates",
    analyteAcronym: "PHOS",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Oxalate",
    analyteAcronym: "OXA",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Hematin",
    analyteAcronym: "HEM",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
  ,
  {
    analyteName: "Artifacts",
    analyteAcronym: "ART",
    unit_of_measure: "/hpf",
    min_level: "0",
    max_level: "0",
    mean: "0",
    std_devi: "0",
    sdplus1: 0,
    sdplus2: 0,
    sdplus3: 0,
    sdminus1: 0,
    sdminus2: 0,
    sdminus3: 0,
    electrolyte: false,
    expected_range: ["Rare", "Small", "Moderate", "Large"],
  }
];